using UnityEngine;

public class CheckSafeZone : MonoBehaviour
{
    public AltarSystemController altarManager;
    private bool isPlayerInSafeZone = false;

    private void OnTriggerEnter(Collider other)
    {
        if (other.CompareTag("Player")) 
        {
            if (!isPlayerInSafeZone) 
            {
                isPlayerInSafeZone = true;
                altarManager.PlayerEnteredSafeZone();  
                Debug.Log("guvenli alana girdi");
            }
        }
    }

    private void OnTriggerExit(Collider other)
    {
        if (other.CompareTag("Player"))  
        {
            if (isPlayerInSafeZone) 
            {
                isPlayerInSafeZone = false;
                altarManager.PlayerExitedSafeZone();
                Debug.Log("guenli alandan cikti");
            }
        }
    }

    public bool IsPlayerInSafeZone()
    {
        return isPlayerInSafeZone;
    }

}

